Terraformのファイルを分割する
ictsc/ictsc-drove pull request #13
Opened 2023-07-25 18:11 UTC by mu-ruU1

## 関連

- #5 

## 概要

- control plane, worker nodeでディレクトリ・ファイルを分離する

## Checklist

- [x] ファイル(main.tf, outputs.tf)の分割
- [ ] リソース命名の変更 ( #6 )
- [ ] 動作確認

## 備考

- リソースの分割はこれで良いか確認お願いします。

2023-07-25 19:29 UTC, logica0419 requested changes
早い反応有難うございます！
分ける部分に関しては問題なくできていそうですが、分け方がちょっと美しくないなぁと思ってしまいます。ちょっと細かいかもしれませんが。
最終的に、今後これを読む人がパッとフォルダを見た瞬間一発で理解できることを目標にしたいので、今できる最大限綺麗にしたいと思っています。

フォルダ分けまでできるのであれば、以下のような形が僕の中では理想ですね
役割をフォルダで分け、その中でリソースの種類をファイルで分けるような形です

- control-plane
  - server.tf
  - disk.tf
- lb
  - server.tf
  - disk,tf
- router
  - server.tf
  - disk.tf
- worker-node
  - server.tf
  - disk.tf
- network
  - external.tf (external switchとsubnet)
  - internal.tf (internal switch)
- main.tf
- output.tf (アウトプットはバラバラのフォルダに分けると逆にわかりづらいと思った)
- var.tf

あくまで僕の意見なので、将来これをメンテする人の気持ちを考えて、もし「こっちの方がいいんじゃない？」みたいな案があったら遠慮なく言って下さい！

2023-07-25 19:29 UTC, logica0419 commented on terraform/worker-node/main.tf
> +}
ここがworker-nodeだけにあるのは美しくないですね…
control-planeとworker-nodeの定義は、どちらもサーバーとディスクのでしかないので、それが違う形をしているというのは少し気持ち悪い感じがします

2023-07-25 19:29 UTC, logica0419 commented on terraform/worker-node/main.tf
> +}
lbは別の役割のインスタンスなので、分けてもらいたいです

2023-07-25 19:29 UTC, logica0419 commented on terraform/worker-node/main.tf
> +}
routerは別の役割のインスタンスなので、分けてもらいたいです

2023-07-26 08:02 UTC, mu-ruU1 commented
確認お願いします。

2023-07-26 11:40 UTC, logica0419 commented
分割は完璧です！ありがとう！！

あとはチェック通ればマージして大丈夫そう
Ansibleのチェック落ちてるのは僕のせいだと思うのでなんとかします
Terraformの方はなんで落ちてるのかなぁという感じですね

2023-07-27 09:10 UTC, mu-ruU1 commented
`プレフィックス-リソースの種類` という形のファイルにしました。

2023-07-31 20:07 UTC, logica0419 approved these changes
完璧ですね！
リソース命名とどっちを先に入れるか…って感じですが(片方にはほぼ作り直しをお願いしなければいけないので)
Yuu君はどう考えてます？

2023-08-01 02:24 UTC, mu-ruU1 commented
お忙しい中すいません。

#17  の進捗的には、あとレビューの修正だけでしょうか？  
それでしたらプルリクをマージしていただいて、meronpannnさんにTerraformのリソース名を変更して頂いたほうが良いのかなと考えています。

2023-08-04 00:45 UTC, logica0419 commented
返信遅れてごめんなさい…

Terraformだけ変更は流石にやめときたいです
整合性保てない状態を一瞬でも作りたくない…

2023-08-04 00:45 UTC, logica0419 approved these changes
Asahiくんからしばらく反応がないので、Yuuくんのやつマージしちゃいましょうか
改めてありがとう！引き続きよろしくお願いします

2023-08-04 04:41 UTC, merged